backend/src/Entity/OrderLine.php
<?php

namespace App\Entity;

use App\Repository\OrderLineRepository;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;


#[ApiResource]
#[ORM\Entity(repositoryClass: OrderLineRepository::class)]
class OrderLine
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\ManyToOne]
    private ?Product $product = null;

    #[ORM\Column]
    private ?int $amount = null;

    #[ORM\Column]
    private ?float $unit_price = null;

    #[ORM\ManyToOne]
    private ?OrderEntity $orderentity = null;

    #[ORM\Column(nullable: true)]
    private ?int $unit_size = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $unit_color = null;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(int $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getUnitPrice(): ?float
    {
        return $this->unit_price;
    }

    public function setUnitPrice(float $unit_price): static
    {
        $this->unit_price = $unit_price;

        return $this;
    }

    public function getOrderentity(): ?OrderEntity
    {
        return $this->orderentity;
    }

    public function setOrderentity(?OrderEntity $orderentity): static
    {
        $this->orderentity = $orderentity;

        return $this;
    }

    public function getUnitSize(): ?int
    {
        return $this->unit_size;
    }

    public function setUnitSize(?int $unit_size): static
    {
        $this->unit_size = $unit_size;

        return $this;
    }

    public function getUnitColor(): ?string
    {
        return $this->unit_color;
    }

    public function setUnitColor(?string $unit_color): static
    {
        $this->unit_color = $unit_color;

        return $this;
    }
}

backend/src/Form/OrderLineType.php
<?php

namespace App\Form;

use App\Entity\OrderLine;
use App\Entity\OrderEntity;
use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderLineType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('amount')
            ->add('unit_price')
            ->add('orderentity', EntityType::class, [
                'class' => OrderEntity::class,
                'choice_label' => 'id',
            ])
            ->add('product', EntityType::class, [
                'class' => Product::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => OrderLine::class,
        ]);
    }
}

backend/src/Controller/OrderLineController.php
<?php

namespace App\Controller;

use App\Entity\OrderLine;
use App\Form\OrderLineType;
use App\Repository\OrderLineRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/order/line')]
class OrderLineController extends AbstractController
{
    #[Route('/', name: 'app_order_line_index', methods: ['GET'])]
    public function index(OrderLineRepository $orderLineRepository): Response
    {
        return $this->render('order_line/index.html.twig', [
            'order_lines' => $orderLineRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_order_line_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $orderLine = new OrderLine();
        $form = $this->createForm(OrderLineType::class, $orderLine);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($orderLine);
            $entityManager->flush();

            return $this->redirectToRoute('app_order_line_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('order_line/new.html.twig', [
            'order_line' => $orderLine,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_line_show', methods: ['GET'])]
    public function show(OrderLine $orderLine): Response
    {
        return $this->render('order_line/show.html.twig', [
            'order_line' => $orderLine,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_order_line_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, OrderLine $orderLine, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OrderLineType::class, $orderLine);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_order_line_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('order_line/edit.html.twig', [
            'order_line' => $orderLine,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_line_delete', methods: ['POST'])]
    public function delete(Request $request, OrderLine $orderLine, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$orderLine->getId(), $request->request->get('_token'))) {
            $entityManager->remove($orderLine);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_order_line_index', [], Response::HTTP_SEE_OTHER);
    }
}

backend/templates/order_line/_delete_form.html.twig
<form method="post" action="{{ path('app_order_line_delete', {'id': order_line.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order_line.id) }}">
    <button class="btn">Delete</button>
</form>

backend/templates/order_line/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit OrderLine{% endblock %}

{% block body %}
    <h1>Edit OrderLine</h1>

    {{ include('order_line/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_order_line_index') }}">back to list</a>

    {{ include('order_line/_delete_form.html.twig') }}
{% endblock %}

backend/templates/order_line/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}OrderLine index{% endblock %}

{% block body %}
    <h1>OrderLine index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Amount</th>
                <th>Unit_price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order_line in order_lines %}
            <tr>
                <td>{{ order_line.id }}</td>
                <td>{{ order_line.amount }}</td>
                <td>{{ order_line.unitPrice }}</td>
                <td>
                    <a href="{{ path('app_order_line_show', {'id': order_line.id}) }}">show</a>
                    <a href="{{ path('app_order_line_edit', {'id': order_line.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_order_line_new') }}">Create new</a>
{% endblock %}

backend/templates/order_line/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New OrderLine{% endblock %}

{% block body %}
    <h1>Create new OrderLine</h1>

    {{ include('order_line/_form.html.twig') }}

    <a href="{{ path('app_order_line_index') }}">back to list</a>
{% endblock %}

backend/templates/order_line/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}OrderLine{% endblock %}

{% block body %}
    <h1>OrderLine</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order_line.id }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ order_line.amount }}</td>
            </tr>
            <tr>
                <th>Unit_price</th>
                <td>{{ order_line.unitPrice }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_order_line_index') }}">back to list</a>

    <a href="{{ path('app_order_line_edit', {'id': order_line.id}) }}">edit</a>

    {{ include('order_line/_delete_form.html.twig') }}
{% endblock %}